/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface': '#f4f6ff',
        'on-secondary': '#eef2ff',
        'on-primary-container': '#4d001c',
        'error-container': '#fb5151',
        'on-secondary-container': '#374c6b',
        'on-secondary-fixed': '#243957',
        'on-surface': '#1a2f4d',
        'on-error': '#ffefee',
        'primary-fixed': '#ff7293',
        'primary-dim': '#a00042',
        'secondary-dim': '#3c5070',
        'error': '#b31b25',
        'tertiary': '#9c3853',
        'on-tertiary-fixed-variant': '#6f1432',
        'primary': '#b5084d',
        'surface-variant': '#ccdeff',
        'inverse-on-surface': '#899ec1',
        'on-surface-variant': '#485c7d',
        'tertiary-fixed-dim': '#f67e99',
        'background': '#f4f6ff',
        'tertiary-dim': '#8d2c48',
        'on-tertiary-container': '#630829',
        'secondary-container': '#c3d8fe',
        'outline-variant': '#99aed2',
        'tertiary-fixed': '#ff8fa7',
        'error-dim': '#9f0519',
        'inverse-primary': '#ff4d80',
        'secondary-fixed-dim': '#b5caf0',
        'secondary-fixed': '#c3d8fe',
        'secondary': '#485c7d',
        'surface-dim': '#bed5ff',
        'primary-fixed-dim': '#ff5483',
        'on-primary-fixed': '#000000',
        'surface-container-high': '#d5e3ff',
        'surface-container': '#dee8ff',
        'surface-tint': '#b5084d',
        'on-primary-fixed-variant': '#5e0024',
        'inverse-surface': '#000e24',
        'on-tertiary-fixed': '#380013',
        'on-error-container': '#570008',
        'on-tertiary': '#ffeff0',
        'outline': '#637899',
        'on-primary': '#ffeff0',
        'surface-container-lowest': '#ffffff',
        'surface-bright': '#f4f6ff',
        'surface-container-low': '#ebf1ff',
        'primary-container': '#ff7293',
        'surface-container-highest': '#ccdeff',
        'on-secondary-fixed-variant': '#415575',
        'on-background': '#1a2f4d',
        'tertiary-container': '#ff8fa7',

        // Register page (Crimson palette)
        'reg-primary': '#ff8d87',
        'reg-primary-container': '#ff7670',
        'reg-primary-dim': '#ff716b',
        'reg-on-primary': '#65000a',
        'reg-surface': '#ffffff',
        'reg-surface-container': '#fcfcfc',
        'reg-surface-container-low': '#fafafa',
        'reg-on-background': '#24020a',
        'reg-outline': '#9f656f',
        'reg-outline-variant': '#6b3942',
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Plus Jakarta Sans'],
        body: ['Plus Jakarta Sans'],
        label: ['Plus Jakarta Sans'],
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      animation: {
        'fade-in':       'fadeIn 0.4s ease-out both',
        'slide-up':      'slideUp 0.4s ease-out both',
        'slide-in-left': 'slideInLeft 0.5s ease-out both',
        'slide-in-right':'slideInRight 0.5s ease-out both',
        'fade-in-slow':  'fadeIn 0.8s ease-out both',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideInLeft: {
          '0%': { transform: 'translateX(-40px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        slideInRight: {
          '0%': { transform: 'translateX(40px)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};
